hooks: {}
members:
  mikefromit:
    role: admin
  mrasband:
    role: admin
  ovv:
    role: admin
  seanson:
    role: admin
  daredevil82:
    role: admin
options:
  billing_email: pythondev.slack@gmail.com
  company: null
  description: Repositories of the pythondev slack community
  email: ''
  location: ''
  name: pyslackers
teams:
  ansible:
    description: Team managing the ansible roles
    id: 2420706
    members:
      mikefromit:
        role: maintainer
      mrasband:
        role: maintainer
      ovv:
        role: maintainer
      seanson:
        role: maintainer
    permission: pull
    privacy: closed
    repositories:
      ansible:
        permission: push
      ansible-role-common:
        permission: push
      ansible-role-docker:
        permission: push
      ansible-role-nginx:
        permission: push
      ansible-role-postgres:
        permission: push
      ansible-role-python:
        permission: push
      ansible-role-redis:
        permission: push
  sir-bot-a-lot:
    description: Sir-bot-a-lot team
    id: 2352690
    members:
      ovv:
        role: maintainer
    permission: pull
    privacy: closed
    repositories:
      sir-bot-a-lot:
        permission: push
      sirbot-plugins:
        permission: push
      sirbot-pythondev:
        permission: push
      sirbot-slack:
        permission: push
